### ISSUE TITLE
workflows don't work

### ISSUE THREAD

**Issue by rainlizard** [X-T-E-R/ComfyUI-EasyCivitai-XTNodes#6]
It says missing `CivitaiCheckpointLoaderSimple` and `CivitaiLoraLoaderStacked`
![Untitled](https://github.com/user-attachments/assets/7a9279c5-404a-4375-ab62-ce47d00381f2)

And the other workflow says missing `LoraLoaderStackedWithPreviews` and `CheckpointLoaderSimpleWithPreviews`

![Untitled](https://github.com/user-attachments/assets/c3ed6aa6-8493-4d63-82ed-27a48a05f22c)

This is honestly all too complicated to figure out without a workflow, so I hope you can remedy this.

**Comment by rainlizard** [comment]
ah, I think the real problem is I can't install it properly. None of the XTNodes are showing up.

I tried both manual install and installing through ComfyUI Manager.

**Comment by UnclePsymon** [comment]
I have the same issue. The nodes are imported just fine, but the nodes just do not show up. I am on Linux and aria2 is installed

```
$ aria2c --version                                   
aria2 version 1.37.0
```

**Comment by X-T-E-R** [comment]
> I have the same issue. The nodes are imported just fine, but the nodes just do not show up. I am on Linux and aria2 is installed
> 
> ```
> $ aria2c --version                                   
> aria2 version 1.37.0
> ```
Hello, I just did a version update. Could you please try updating and see if it works?

**Comment by UnclePsymon** [comment]
Nope, the nodes are still not there. I updated Comfy and all custom nodes and there is no import error with your nodes.

**Comment by UnclePsymon** [comment]
I just tried it on a different (Ubuntu) installation to make sure that it is not related to my main system. It is not working there either ;(

**Comment by lunarlabs** [comment]
Nodes aren't loading for me either. I enabled the debug flags in the init and this is what comes out on the log:
`XTNodes: Failed to import D:\StabilityMatrixData\Packages\ComfyUI\custom_nodes\ComfyUI-EasyCivitai-XTNodes\civitaiNodes\civitai_url_nodes.py / "'DynaBox' object has no attribute 'token'"`

**Comment by X-T-E-R** [comment]
> Nodes aren't loading for me either. I enabled the debug flags in the init and this is what comes out on the log: `XTNodes: Failed to import D:\StabilityMatrixData\Packages\ComfyUI\custom_nodes\ComfyUI-EasyCivitai-XTNodes\civitaiNodes\civitai_url_nodes.py / "'DynaBox' object has no attribute 'token'"`

OK，Thank you ! I know where the problem is. Please hold on, I'll fix it right away.

**Comment by X-T-E-R** [comment]
> I just tried it on a different (Ubuntu) installation to make sure that it is not related to my main system. It is not working there either ;(

The reason is that the token option wasn't configured. I assumed it would be set by default for downloading NSFW models: the user would copy .secrets.toml.example to .secrets.toml and fill in the token. However, the token is not strictly required; regular models don't need a token. You could try it now, it should be working.

**Comment by UnclePsymon** [comment]
It does! Thanks a bunch!
